// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package userclient

import (
	"context"

	"user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Article           = user.Article
	InsertArticleReq  = user.InsertArticleReq
	InsertArticleResp = user.InsertArticleResp
	InsertUserReq     = user.InsertUserReq
	InsertUserResp    = user.InsertUserResp
	ListArticleReq    = user.ListArticleReq
	ListArticleResp   = user.ListArticleResp
	QueryUserReq      = user.QueryUserReq
	QueryUserResp     = user.QueryUserResp
	Request           = user.Request
	Response          = user.Response
	SayHelloReq       = user.SayHelloReq
	SayHelloResp      = user.SayHelloResp

	User interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		SayHello(ctx context.Context, in *SayHelloReq, opts ...grpc.CallOption) (*SayHelloResp, error)
		QueryUser(ctx context.Context, in *QueryUserReq, opts ...grpc.CallOption) (*QueryUserResp, error)
		ListArticle(ctx context.Context, in *ListArticleReq, opts ...grpc.CallOption) (*ListArticleResp, error)
		InsertUser(ctx context.Context, in *InsertUserReq, opts ...grpc.CallOption) (*InsertUserResp, error)
		InsertArticle(ctx context.Context, in *InsertArticleReq, opts ...grpc.CallOption) (*InsertArticleResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultUser) SayHello(ctx context.Context, in *SayHelloReq, opts ...grpc.CallOption) (*SayHelloResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SayHello(ctx, in, opts...)
}

func (m *defaultUser) QueryUser(ctx context.Context, in *QueryUserReq, opts ...grpc.CallOption) (*QueryUserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.QueryUser(ctx, in, opts...)
}

func (m *defaultUser) ListArticle(ctx context.Context, in *ListArticleReq, opts ...grpc.CallOption) (*ListArticleResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ListArticle(ctx, in, opts...)
}

func (m *defaultUser) InsertUser(ctx context.Context, in *InsertUserReq, opts ...grpc.CallOption) (*InsertUserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.InsertUser(ctx, in, opts...)
}

func (m *defaultUser) InsertArticle(ctx context.Context, in *InsertArticleReq, opts ...grpc.CallOption) (*InsertArticleResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.InsertArticle(ctx, in, opts...)
}
