// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload/file",
				Handler: UploadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/:id",
				Handler: UpdateUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/refresh",
				Handler: RefreshTokenHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sse/with/req",
				Handler: sseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sse/without/resp",
				Handler: sserespHandler(serverCtx),
			},
		},
		rest.WithSSE(),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/profile/:userId",
				Handler: GetProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/profile/:userId",
				Handler: UpdateProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
