// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type LogoutResp struct {
	Success bool   `json:"success"`
	Message string `json:"message,omitempty"`
}

type ProfileReq struct {
	UserId int64 `path:"userId"`
}

type ProfileResp struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type SseReq struct {
	Body string `json:"body"`
}

type SseResp struct {
	Msg string `json:"msg"`
}

type UpdateProfileReq struct {
	UserId   int64  `path:"userId"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

type UpdateProfileResp struct {
	Success bool `json:"success"`
}

type UploadResp struct {
	Filename string `json:"filename"`
	Size     int64  `json:"size"`
	URL      string `json:"url"`
}

type UserInfoReq struct {
	Id int64 `path:"id"`
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserUpdateReq struct {
	Id       int64  `path:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserUpdateResp struct {
	Info string `json:"info"`
}
