// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type SseReq struct {
	Body string `json:"body"`
}

type SseResp struct {
	Msg string `json:"msg"`
}

type UserInfoReq struct {
	Id int64 `path:"id"`
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserUpdateReq struct {
	Id       int64  `path:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserUpdateResp struct {
	Info string `json:"info"`
}
