// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package server

import (
	"context"

	"user/rpc/internal/logic"
	"user/rpc/internal/svc"
	"user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserServer) SayHello(ctx context.Context, in *user.SayHelloReq) (*user.SayHelloResp, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}

func (s *UserServer) QueryUser(ctx context.Context, in *user.QueryUserReq) (*user.QueryUserResp, error) {
	l := logic.NewQueryUserLogic(ctx, s.svcCtx)
	return l.QueryUser(in)
}

func (s *UserServer) ListArticle(ctx context.Context, in *user.ListArticleReq) (*user.ListArticleResp, error) {
	l := logic.NewListArticleLogic(ctx, s.svcCtx)
	return l.ListArticle(in)
}

func (s *UserServer) InsertUser(ctx context.Context, in *user.InsertUserReq) (*user.InsertUserResp, error) {
	l := logic.NewInsertUserLogic(ctx, s.svcCtx)
	return l.InsertUser(in)
}

func (s *UserServer) InsertArticle(ctx context.Context, in *user.InsertArticleReq) (*user.InsertArticleResp, error) {
	l := logic.NewInsertArticleLogic(ctx, s.svcCtx)
	return l.InsertArticle(in)
}

func (s *UserServer) Pusher(ctx context.Context, in *user.PusherReq) (*user.PusherResp, error) {
	l := logic.NewPusherLogic(ctx, s.svcCtx)
	return l.Pusher(in)
}
